version: 2.1
jobs:
  build_test:
      docker:
        - image: cimg/node:20.12.0
      steps:
        - checkout
        - run:
             name: install dependencies
             command: |
                npm install --save

  build_docker_image:
    docker:
      - image: cimg/node:20.12.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
             docker build -t nodeapp1 -t happy361/nodeapp1:latest .
             echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
             docker push happy361/nodeapp1:latest
workflows:
   build_test:
      jobs:
        - build_test
        - build_docker_image:
                  requires:
                      - build_test