version: 2.1

jobs:
  build_test:
    docker:
      - image: cimg/node:20.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install

  build_docker_image:
    docker:
      - image: cimg/node:20.12.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            if [ "$CIRCLE_BRANCH" = "development" ]; then
              docker build -t nodeapp20:latest -t happy361/nodeapp20:latest .
              echo Lenovo361gb | docker login -u happy361 --password-stdin
              docker push happy361/nodeapp20:latest
            else
              docker build -t nodeapp20:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7} -t happy361/nodeapp20:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7} .
              echo Lenovo361gb | docker login -u happy361 --password-stdin
              docker push happy361/nodeapp20:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_test
      - build_docker_image:
          requires:
            - build_test
          filters:
            tags:
              only: /^v.*/
