version: 2.1
jobs:
  build_test:
      docker:
        - image: circleci/node:20
      steps:
        - checkout
        - run:
             name: install dependencies
             command: |
                npm install --save
#  build_docker_image:
    docker:
      - image: circleci/node:20
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
             docker build -t nodejsapp1 -t happy361/nodejsapp1:latest .
             echo $Docker_PASSWORD | docker login -u happy361 --password-stdin
             docker push happy361/nodejsapp1:latest
workflows:
   build_test:
      jobs:
        - build_test
        - build_docker_image                                
