version: 2.1

jobs:
  build_test:
    docker:
      - image: cimg/node:20.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install

  build_docker_image:
    docker:
      - image: cimg/node:20.12.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t nodeapp20 -t happy361/nodeapp20:${CIRCLE_TAG} .
            echo Lenovo361gb | docker login -u happy361 --password-stdin
            docker push happy361/nodeapp20:${CIRCLE_TAG}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_test
      - build_docker_image:
          requires:
            - build_test
          filters:
            tags:
              only: /^v.*/
# adding